# This file contains instructions for the build server Travis
# The build is running on https://travis-ci.com/.
sudo: required
dist: trusty
language: node_js
node_js:
- '10.16.0'
env:
  global:
  - BETA_RC_TAG_REGEX="^microfrontend-platform-[0-9]+.[0-9]+.[0-9]+-" # Matches 'next' versions x.x.x-beta and x.x.x-rc (npm tag: next)
  - RELEASE_TAG_REGEX="^microfrontend-platform-[0-9]+.[0-9]+.[0-9]+$" # Matches 'stable' versions x.x.x (npm tag: latest)
  - secure: "hghs643vBOf+zs0J3VdRkwq0eHJrf56iP5z4Mk7lUWsZCRwfobghsfpxP3ZTlqvlGM3I/bRPZf+RJVOr8tDrViDhfrB05LnPI0LIp4MqAPpovf7TaEqsN+Lj135qcYFnKpvHN/j0QXFonqdvIVOaP2HNm1mqFRJ/kUkQcZKZOGmsM75g3a73ZYdzJpsq5bd2iYS59vs/GuUiyBlAtACE2v6AOAeTNVCcAbw2OShpWuLB698r581SRvs0pW2oGtUtNfSbGjcr6VYHQimMuwxHJEI7EnL/wqgXPY1iiVEyzbEbUU1cRK4Xtcd5512XcpdJHZhlTw4UmZG/pXTzqa9O4DFyTGHfcNUJWG8KBblwL3VUrUazyvudpodWSpePUQBi/e9h/yrKfM28huNL+CtMGiHU5uGus/oK9pA5MPgmO+konQ1esHAvUhTWVto3e/gzuX8mDaTqBZ3YNe8JW+gImk5L6ZrFrMM8ZzbCZM9UzY3D3khgsJpD8tHBz4gHndBh+cTFAmENUQi9aT/tdKHxMmKgKS+xTRTja+WIwzjUZBWl7aZ6/GcAI9fme13VOYJaVuXF8AAu9iJFjDyDYYK+xor3eed/+FUF4C6FogiAm2PqF1QcMC5cjaq8bWmuYwhgvY4HU2daoa1Wuf9SQPg46WBXlU8VFmPFXG9CMyKRfWI=" # $NOW_TOKEN
  - secure: "S3fGMms92geqAHCJXPhN66iLGYh18NOXYHLjb7Jwg/ohLWhAUcFkn04NkeS0QXXmQGVPzqITddT20PMBcyEE8MJVRpY4s89VCLORxI8qeNcf3FiG/Rk5zGQ3hvf+kzjupWXutHKLXZLL+mWiKM9HNfvLqumDC71J+fYmOuDwGVXRKw4elscTmyVaqoPkqS7i4cfJCynbTPRDgB57vLxJCARuRt95m685MAezg/F8h1V4/9LK2Ko347Khn3KUNPl1f3L1puGiHYtEdtU9f+WzBgmKEgJIEjxuoJqEsWAuKu0aew5bl/pWwtDRc9z6PF1atyR64rrvTeKUrfKEsFgN41x7k7gs1hZmgVsYzpwN+PTeK3H+Egfp1kTjIix4MwpbT9Eyb+unRPmyxypIMeCLGHXb8JBFOSBjDpHG7NeySVfFkSu5po495W7wMVgE7GMdrDjQTBfTrja4oHKnfi4PmYzWEcVASYCrFKYnZPkb7NJhWz4gArS4F+juxfwbMSDL96dWTTbB9b+MXgkB0l14lYlLE8Xi0dXIwoRGVNc1eJ8yf3zeQgaLGbdkSAeJ45w9tnylRIQDf5roEHS//UQ1TGGuv4tvgwr4VC1jn+sE9U9sh/LuReL5/XF2YtfZClQsAmwOmxPN62hA+8JL8Zbo523Zbyi9fEXYIca5DdsRH6E=" # $NPM_TOKEN
install:
- npm ci
jobs:
  include:
  - stage: "Lint stage"
    name: "lints all libraries"
    script:
      - npm run lint-all
  - stage: "Build stage"
    name: "builds all, tests all, deploys apps (if branch=issue/198) to 'https://zeit.co/scion', publishes libraries to NPM (if branch=issue/198 AND if release tag)"
    script:
    - npm run build-all
    - npm run test-all:headless
    - npm run e2e-all:headless
    deploy:
      # Deploy microfrontend-apps
      - provider: script
        script: bash ./travis-scripts/now-deploy.sh $TRAVIS_BUILD_DIR dist/apps/microfrontend-apps $NOW_TOKEN
        skip_cleanup: true
        on:
          branch: issue/198
          tags: true
      - provider: script
        script: bash ./travis-scripts/now-deploy.sh $TRAVIS_BUILD_DIR dist/apps/microfrontend-apps $NOW_TOKEN
        skip_cleanup: true
        on:
          branch: issue/198
          tags: false
      # Publish @scion/microfrontend-platform
      - provider: script
        script: bash ./travis-scripts/npm-publish.sh $TRAVIS_BUILD_DIR dist/scion/microfrontend-platform $NPM_TOKEN "--tag next"
        skip_cleanup: true
        on:
          branch: issue/198
          tags: true
          condition: "$TRAVIS_TAG =~ $BETA_RC_TAG_REGEX"
      # Publish @scion/toolkit
      - provider: script
        script: bash ./travis-scripts/npm-publish.sh $TRAVIS_BUILD_DIR dist/scion/toolkit $NPM_TOKEN "--tag next"
        skip_cleanup: true
        on:
          branch: issue/198
          tags: true
          condition: "$TRAVIS_TAG =~ $BETA_RC_TAG_REGEX"
